version: "3.8"

services:
  mysql_db:
    container_name: 'mysql_db'
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpMyAdmin:
    depends_on:
      - mysql_db
    container_name: 'phpMyAdmin'
    image: phpmyadmin:latest
    restart: always
    environment:
      - UPLOAD_LIMIT=1G
      - PMA_ARBITRARY=1
    ports:
      - protocol: tcp
        published: 9000
        target: 80
